export const sampleProducts =

    [
        {
            "active_ingredients": "herbal products, mango leaves",
            barcode: "",
            "category": "SYRUP",
            "caution": "do not take on empty stomach",
            "contraindications": "",
            "cost_price": 16,
            "created_on": "2021-06-05 19:22:16",
            "current_stock": 4,
            "description": "herbal cough syrups",
            "drug_info": "",
            "expiry": "2023-02-02",
            "generic_name": "",
            "indications": "cough",
            "is_drug": "yes",
            "last_modified": "2021-06-05 19:22:16",
            "last_stock_modification": "2023-02-21 18:01:25",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "APDYL H COUGH SYRUP",
            "notes": "",
            "price": 26.6,
            "shelf": "",
            "size": "100ml",
            "status": "",
            "unit": "bottle",
            id: 1

        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "SYRUP",
            "caution": "",
            "contraindications": "",
            "cost_price": 6.6,
            "created_on": "2021-06-05 19:23:26",
            "current_stock": 2,
            "description": "herbal cough syrups",
            "drug_info": "",
            "expiry": "2024-04-25",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-06-05 19:23:26",
            "last_stock_modification": "2023-02-21 18:01:27",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "ASCORYL SYRUP 125",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 9,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "bottle",
            id: 2
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 3.52,
            "created_on": "2021-06-05 21:04:12",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2023-02-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-06-05 21:4:12",
            "last_stock_modification": "2023-02-21 18:04:53",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "CHOCHO SOAP",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 4.1,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "piece",
            id: 3
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "SYRUP",
            "caution": "",
            "contraindications": "",
            "cost_price": 12.8,
            "created_on": "2021-06-05 21:07:40",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2023-04-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-12-10 2:53:39",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 2,
            "name": "KIDIVITE MULTIVITAMIN DROPS",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 17,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "bottle",
            id: 4
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 17,
            "created_on": "2021-06-05 21:13:53",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2022-11-22",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-06-05 21:13:53",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "KINGDOM GARLIC CAPS",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 22.61,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "pack",
            id: 5
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 14.5,
            "created_on": "2021-06-05 21:16:05",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2022-02-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-06-05 21:16:5",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "KINGDOM GINSENG POWER CAPS",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 20,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "pack",
            id: 6
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "SYRUP",
            "caution": "",
            "contraindications": "",
            "cost_price": 25.5,
            "created_on": "2021-06-05 21:17:21",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2022-02-24",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-10-27 3:29:29",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "LIVING BITTERS MIXT 200ML",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 34,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "bottle",
            id: 7
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "CREAM",
            "caution": "",
            "contraindications": "",
            "cost_price": 3.3,
            "created_on": "2021-06-05 21:19:29",
            "current_stock": 0,
            "description": "herbal cough syrups",
            "drug_info": "",
            "expiry": "2023-02-24",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-10-27 3:29:44",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "MERCY OINTMENT 32G",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 4.3,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "piece",
            id: 8
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "SYRUP",
            "caution": "",
            "contraindications": "",
            "cost_price": 26.98,
            "created_on": "2021-06-05 21:24:39",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2024-05-30",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2022-08-24 16:33:37",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 3,
            "name": "SEVEN SEAS C.L.O. SYRUP",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 35,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "bottle",
            id: 9
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 12.1,
            "created_on": "2021-06-05 21:27:01",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2023-02-24",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-06-05 21:27:1",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "SIBI MAN CAPSULES",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 15.7,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "capsule",
            id: 10
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 12.1,
            "created_on": "2021-06-05 21:29:55",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2023-03-25",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-06-05 21:29:55",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 100,
            "min_stock": 1,
            "name": "SIBI WOMAN CAPSULE",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 16.09,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "pack",
            id: 11
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Uncategorised",
            "caution": "",
            "contraindications": "",
            "cost_price": 11,
            "created_on": "2021-06-05 21:34:19",
            "current_stock": 0,
            "description": "herbal caps",
            "drug_info": "",
            "expiry": "2022-02-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-06-05 21:34:19",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "TAABEA CAPS",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 14.3,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "capsule",
            id: 12
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 19.5,
            "created_on": "2021-06-05 21:38:22",
            "current_stock": -1,
            "description": "herbal cough syrups",
            "drug_info": "",
            "expiry": "2024-04-30",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-10-27 3:30:0",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "TAABEA MIXTURE",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 26,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "HERBAL",
            id: 13
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "EYE DROPS",
            "caution": "",
            "contraindications": "",
            "cost_price": 22.98,
            "created_on": "2021-06-05 21:41:57",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2023-06-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-06-05 21:41:57",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 1,
            "name": "TEARS NATURAL EYE DROPS",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 31,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "bottle",
            id: 14
        },
        {
            "active_ingredients": "",
            "barcode": "0001254",
            "category": "TABLET",
            "caution": "",
            "contraindications": "",
            "cost_price": 5.8,
            "created_on": "2021-06-05 22:12:14",
            "current_stock": 288,
            "description": "herbal caps",
            "drug_info": "",
            "expiry": "2025-09-28",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2022-11-04 13:08:46",
            "last_stock_modification": "2023-02-21 18:05:11",
            "markup": 1.33,
            "max_stock": 200,
            "min_stock": 10,
            "name": "DIOSMIN DAFLON 500MG TAB",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 7.71,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "tablet",
            id: 15
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 9.24,
            "created_on": "2021-06-06 12:03:10",
            "current_stock": 0,
            "description": "PLASTER",
            "drug_info": "",
            "expiry": "2025-03-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-12-10 2:55:10",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 2,
            "name": "PLASTER 2in",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 12.3,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "piece",
            id: 16
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 7.38,
            "created_on": "2021-06-06 12:07:12",
            "current_stock": 0,
            "description": "herbal caps",
            "drug_info": "",
            "expiry": "2024-03-25",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-12-10 2:55:23",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 10,
            "min_stock": 2,
            "name": "PLASTER 3in",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 9.8,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "piece",
            id: 17
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 11.28,
            "created_on": "2021-06-06 12:09:35",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2025-05-25",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2022-08-02 14:53:51",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 2,
            "name": "PLASTER 4in",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 15,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "piece",
            id: 18
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 4,
            "created_on": "2021-06-06 12:10:47",
            "current_stock": 0,
            "description": "herbal caps",
            "drug_info": "",
            "expiry": "2025-04-24",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-10-27 3:30:20",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 10,
            "min_stock": 1,
            "name": "GAUZE 2in",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 5.3,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "piece",
            id: 19
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 0.1195,
            "created_on": "2021-06-06 12:13:42",
            "current_stock": 0,
            "description": "",
            "drug_info": "",
            "expiry": "2026-03-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2022-08-25 19:30:17",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 1000,
            "min_stock": 10,
            "name": "PLASTER STRIPS",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 0.5,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "piece",
            id: 20
        },
        {
            "active_ingredients": "",
            "barcode": "0001260",
            "category": "INJECTION",
            "caution": "",
            "contraindications": "",
            "cost_price": 500,
            "created_on": "2021-06-06 17:26:16",
            "current_stock": 10,
            "description": "herbal caps",
            "drug_info": "",
            "expiry": "2023-02-25",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2022-09-23 15:21:49",
            "last_stock_modification": "",
            "markup": 1.3,
            "max_stock": 10,
            "min_stock": 1,
            "name": "HYALURORIC ACID INJ",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 650,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "vial",
            id: 21
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 4.1,
            "created_on": "2021-06-06 19:19:01",
            "current_stock": 14,
            "description": "",
            "drug_info": "",
            "expiry": "2025-09-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-10-25 3:4:58",
            "last_stock_modification": "2023-02-21 18:01:21",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 2,
            "name": "ALVARO DRINK",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 5.5,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "bottle",
            id: 22
        },
        {
            "active_ingredients": "",
            "barcode": "",
            "category": "Miscellaneous",
            "caution": "",
            "contraindications": "",
            "cost_price": 4.5833,
            "created_on": "2021-06-06 19:38:41",
            "current_stock": 2,
            "description": "herbal capsules",
            "drug_info": "",
            "expiry": "2025-02-23",
            "generic_name": "",
            "indications": "",
            "is_drug": "yes",
            "last_modified": "2021-11-15 10:41:25",
            "last_stock_modification": "",
            "markup": 1.33,
            "max_stock": 20,
            "min_stock": 2,
            "name": "MALTA GUINESS BOTTLE",
            "notes": "",
            "picture": "",
            "preferred_vendor": "",
            "pregnancy": "",
            "price": 6.1,
            "shelf": "",
            "side_effects": "",
            "size": "",
            "status": "",
            "unit": "bottle",
            id: 23
        }];


export const samplePurchases = [
    {
        date: '2023-03-19',
        created_by: '1',
        invoice: '123',
        vendor: '1',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-04-19',
        created_by: '1',
        invoice: '223',
        vendor: '1',
        items: `[
                {
                    "product": 22,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 4,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20.3,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 2.7,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-04-30',
        created_by: '1',
        invoice: '4123',
        vendor: '1',
        items: `[
                {
                    "product": 22,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-05-19',
        created_by: '1',
        invoice: '5123',
        vendor: '1',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-06-19',
        created_by: '1',
        invoice: '6123',
        vendor: '2',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 5,
                    "selling_price": 10,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5.5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 2,
                    "quantity": 15,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-07-19',
        created_by: '1',
        invoice: '7123',
        vendor: '2',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-08-19',
        created_by: '1',
        invoice: '8123',
        vendor: '1',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-09-19',
        created_by: '1',
        invoice: '9123',
        vendor: '1',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-10-19',
        created_by: '1',
        invoice: '10123',
        vendor: '2',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-03-16',
        created_by: '1',
        invoice: '11123',
        vendor: '1',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-02-19',
        created_by: '1',
        invoice: '13123',
        vendor: '1',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-05-01',
        created_by: '1',
        invoice: '14123',
        vendor: '2',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },
    {
        date: '2023-12-19',
        created_by: '1',
        invoice: '15123',
        vendor: '1',
        items: `[
                {
                    "product": 1,
                    "created_by": 1,
                    "price": 3,
                    "quantity": 9,
                    "selling_price": 4,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 2,
                    "created_by": 1,
                    "price": 5,
                    "quantity": 20,
                    "selling_price": 7,
                    "unit": "tablet",
                    "markup": 1.3,
                    "expiry": "2024-01-02"
                },
                {
                    "product": 5,
                    "created_by": 1,
                    "price": 20,
                    "quantity": 50,
                    "selling_price": 30,
                    "unit": "strip",
                    "markup": 1.5,
                    "expiry": "2025-01-02"
                }
            ]`,
        user_id: 1
    },

]


